name: Build main
on:
  push:
    branches: [main]

jobs:
  build-and-release:
    name: Build Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      -  name: Build and push
         uses: docker/build-push-action@v3
         with:
          context: .
          push: true
          tags: mronadasky/lookscanned.io:latest
